#Configuration
#Update frequency, in milliseconds (300000 = 5 minutes)
cache_update_frequency: 300000
#Message format, %member% is replaced with the member display name, %message% is replaced with the message
default_name_color: "&b"
message_format: "&f%prefix% %member% %suffix%&8>&f %message%"
#NOTE: Adding hover text may break some plugins! If you're having issues, set this to no
hover_text: yes
#datatype: <flat/db>
datatype: flat
#Only if datatype is set to DB
db_username: username
db_password: password
db_database: mydb
db_url: example.org
db_port: 3306
#Only if datatype is set to flat
players:
  cf173d12-c079-4213-81f0-9daa0acfd9bd:
    system: bpray